// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

type Product struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	PriceInCents int64  `json:"price_in_cents"`
	Quantity     int64  `json:"quantity"`
	CreatedAt    string `json:"created_at"`
}
