// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

type Order struct {
	ID         int64  `json:"id"`
	CustomerID int64  `json:"customer_id"`
	CreatedAt  string `json:"created_at"`
}

type OrderItem struct {
	ID           int64 `json:"id"`
	OrderID      int64 `json:"order_id"`
	ProductID    int64 `json:"product_id"`
	Quantity     int64 `json:"quantity"`
	PriceInCents int64 `json:"price_in_cents"`
}

type Product struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	PriceInCents int64  `json:"price_in_cents"`
	Quantity     int64  `json:"quantity"`
	CreatedAt    string `json:"created_at"`
}
